export enum TransactionType {
    TRANSFERT = 'TRANSFERT',
    RETRAIT = 'RETRAIT',
    PAIEMENT = 'PAIEMENT',
    ABONNEMENT = 'ABONNEMENT',
    DEPOT = 'DEPOT',
    PAYMENT_REQUEST = 'REQUETE DE PAIEMENT'
}